### PR TITLE
Movement branch - Added Left/Right controller joystick movement of the camera

### PR DESCRIPTION
**Pull request by Bamboogamer**
Allows for movement of the XR Rig so you don't have to move the objects in the scene to the rig to test them.

I also cleaned up the hierarchy of the XR Rigs and moved the cameras to correct positions. Interactions with objects, like grabbing the sanitizer, the object follows the hand even while moving

### CODE REVIEW

**Comment by Jflyer45** [comment]
My comment from discord: "Tested it out, the walking and view snap works good! I did find a bug though, if you pick something up, movement and especially the view snap breaks movement. You can't move forward and sometimes you start forcibly moving backwards. Weird. If you can't recreated, I'll take a video of it."

**Comment by tjlauer** [comment]
I'll let Jeremy review this one

**Comment by Jflyer45** [comment]
Would you like me to merge even though there is a bug, of which you can fix later? Because your changes I assume are isolated to a scene I doesn't really matter either way

**Comment by tjlauer** [comment]
@Jflyer45
- [ ] 1) Create a new issue for the bug
- [ ] 2) Link that issue to this PR
<hr>

@Bamboogamer
- [ ] 1) Fix the bug
- [ ] 2) Commit changes to the `movement-branch` branch
- [ ] 3) Mark this PR as `Open` by clicking the **`Ready for review`** button

**Comment by tjlauer** [comment]
Fixed conflict with `UserSettings/EditorUserSettings.asset`

**Review by tjlauer — APPROVED** [review]
Looks good!

**Pull request merged**
